# Generated by Django 3.1.3 on 2020-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Category 1', 'Category 1'), ('Football', 'Football'), ('Window Cleaning', 'Window Cleaning')], max_length=50),
        ),
    ]
