# Generated by Django 3.1.3 on 2020-11-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.FloatField(default=50.0),
        ),
    ]
