# Generated by Django 3.1.3 on 2020-11-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
