# Generated by Django 3.1.3 on 2020-11-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
